### ISSUE TITLE
[Bug]: Main android navigation color inconsistency in dark mode

### ISSUE THREAD

**Issue by ImBIOS** [dzikirqu/dzikirqu-android#9]
### Contact Details

hi@imam.dev

### What happened?

Main android navigation is sometimes white and sometimes black in android dark mode with follow system theme setting.

### Version

2.6.10

### What android version are you seeing the problem on?

Android 11

### Relevant screenshots and details

# Homepage (the bug is here)
![image](https://user-images.githubusercontent.com/41441643/182347484-9dfc4aa9-891e-4fef-aa3b-60c37df5c12a.png)

# Setting page (normal)
![image](https://user-images.githubusercontent.com/41441643/182347631-4325cdac-f868-4f6e-82a5-313f4a4bd4f9.png)

### How to reproduce bug

Just open the app using the main android navigation activated.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by wagyufari** [comment]
Fixed on https://github.com/dzikirqu/dzikirqu-android/pull/17
